# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Oct 23 13:01:53 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 594)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/basic-ui/icons/111267-basic-ui/svg/eye-close-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setDocumentMode(False)
        self.mainWindowContents = QtGui.QWidget(MainWindow)
        self.mainWindowContents.setObjectName("mainWindowContents")
        self.gridLayout = QtGui.QGridLayout(self.mainWindowContents)
        self.gridLayout.setObjectName("gridLayout")
        self.lineVertical = QtGui.QFrame(self.mainWindowContents)
        self.lineVertical.setFrameShape(QtGui.QFrame.VLine)
        self.lineVertical.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineVertical.setObjectName("lineVertical")
        self.gridLayout.addWidget(self.lineVertical, 0, 1, 3, 1)
        self.line = QtGui.QFrame(self.mainWindowContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 2, 1, 1)
        self.framesWidget = FramesQWidget(self.mainWindowContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framesWidget.sizePolicy().hasHeightForWidth())
        self.framesWidget.setSizePolicy(sizePolicy)
        self.framesWidget.setObjectName("framesWidget")
        self.framesGridLayout = QtGui.QGridLayout(self.framesWidget)
        self.framesGridLayout.setObjectName("framesGridLayout")
        self.plotFrameALabel = QtGui.QLabel(self.framesWidget)
        self.plotFrameALabel.setObjectName("plotFrameALabel")
        self.framesGridLayout.addWidget(self.plotFrameALabel, 0, 0, 1, 1)
        self.plotFrameASpinBox = QtGui.QSpinBox(self.framesWidget)
        self.plotFrameASpinBox.setMinimum(1)
        self.plotFrameASpinBox.setObjectName("plotFrameASpinBox")
        self.framesGridLayout.addWidget(self.plotFrameASpinBox, 0, 1, 1, 1)
        self.plotFrameBLabel = QtGui.QLabel(self.framesWidget)
        self.plotFrameBLabel.setObjectName("plotFrameBLabel")
        self.framesGridLayout.addWidget(self.plotFrameBLabel, 1, 0, 1, 1)
        self.plotFrameBSpinBox = QtGui.QSpinBox(self.framesWidget)
        self.plotFrameBSpinBox.setMinimum(1)
        self.plotFrameBSpinBox.setProperty("value", 2)
        self.plotFrameBSpinBox.setObjectName("plotFrameBSpinBox")
        self.framesGridLayout.addWidget(self.plotFrameBSpinBox, 1, 1, 1, 1)
        self.framesPlotLayout = QtGui.QVBoxLayout()
        self.framesPlotLayout.setObjectName("framesPlotLayout")
        self.framesGridLayout.addLayout(self.framesPlotLayout, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.framesWidget, 0, 0, 3, 1)
        self.odWidget = OdQWidget(self.mainWindowContents)
        self.odWidget.setObjectName("odWidget")
        self.odLayout = QtGui.QVBoxLayout(self.odWidget)
        self.odLayout.setObjectName("odLayout")
        self.gridLayout.addWidget(self.odWidget, 2, 2, 1, 1)
        self.inputWidget = QtGui.QWidget(self.mainWindowContents)
        self.inputWidget.setObjectName("inputWidget")
        self.formLayout = QtGui.QFormLayout(self.inputWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.numberOfFramesLabel = QtGui.QLabel(self.inputWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfFramesLabel.sizePolicy().hasHeightForWidth())
        self.numberOfFramesLabel.setSizePolicy(sizePolicy)
        self.numberOfFramesLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.numberOfFramesLabel.setObjectName("numberOfFramesLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.numberOfFramesLabel)
        self.numberOfFramesSpinBox = QtGui.QSpinBox(self.inputWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfFramesSpinBox.sizePolicy().hasHeightForWidth())
        self.numberOfFramesSpinBox.setSizePolicy(sizePolicy)
        self.numberOfFramesSpinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numberOfFramesSpinBox.setSuffix("")
        self.numberOfFramesSpinBox.setProperty("value", 4)
        self.numberOfFramesSpinBox.setObjectName("numberOfFramesSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.numberOfFramesSpinBox)
        self.setBackgroundFrameLabel = QtGui.QLabel(self.inputWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setBackgroundFrameLabel.sizePolicy().hasHeightForWidth())
        self.setBackgroundFrameLabel.setSizePolicy(sizePolicy)
        self.setBackgroundFrameLabel.setObjectName("setBackgroundFrameLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.setBackgroundFrameLabel)
        self.setBackgroundFrameSpinBox = QtGui.QSpinBox(self.inputWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setBackgroundFrameSpinBox.sizePolicy().hasHeightForWidth())
        self.setBackgroundFrameSpinBox.setSizePolicy(sizePolicy)
        self.setBackgroundFrameSpinBox.setMinimum(1)
        self.setBackgroundFrameSpinBox.setProperty("value", 2)
        self.setBackgroundFrameSpinBox.setObjectName("setBackgroundFrameSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.setBackgroundFrameSpinBox)
        self.sourceFolderLabel = QtGui.QLabel(self.inputWidget)
        self.sourceFolderLabel.setObjectName("sourceFolderLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sourceFolderLabel)
        self.sourceFolderLineEdit = QtGui.QLineEdit(self.inputWidget)
        self.sourceFolderLineEdit.setObjectName("sourceFolderLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sourceFolderLineEdit)
        self.gridLayout.addWidget(self.inputWidget, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.mainWindowContents)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 772, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlot = QtGui.QMenu(self.menuBar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionHome = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/basic-ui/icons/111267-basic-ui/svg/home-button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon1)
        self.actionHome.setObjectName("actionHome")
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/basic-ui/icons/111267-basic-ui/svg/refresh-arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon2)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionInfo = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/basic-ui/icons/111267-basic-ui/svg/left-justification-button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon3)
        self.actionInfo.setObjectName("actionInfo")
        self.menuFile.addAction(self.actionHome)
        self.menuPlot.addAction(self.actionRefresh)
        self.menuHelp.addAction(self.actionInfo)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionRefresh)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ELENA", None, QtGui.QApplication.UnicodeUTF8))
        self.plotFrameALabel.setText(QtGui.QApplication.translate("MainWindow", "Plot frame A", None, QtGui.QApplication.UnicodeUTF8))
        self.plotFrameBLabel.setText(QtGui.QApplication.translate("MainWindow", "Plot frame B", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfFramesLabel.setText(QtGui.QApplication.translate("MainWindow", "Number of frames", None, QtGui.QApplication.UnicodeUTF8))
        self.setBackgroundFrameLabel.setText(QtGui.QApplication.translate("MainWindow", "Set background frame", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceFolderLabel.setText(QtGui.QApplication.translate("MainWindow", "Source folder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))

from .odqwidget import OdQWidget
from .framesqwidget import FramesQWidget
from . import resources_rc
